version: '3.3'

services:
  dds_be:
    container_name: "dds_be"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/paths:/dds_app/app/data
    depends_on:
      - "dds_db"
    ports:
        - 3001:3001
  dds_db:
    image: "postgres"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
        - 5432:5432
  mqtt_broker:
    image: hivemq/hivemq4
    ports:
        - 8080:8080
        - 1883:1883
